class AppStrings {
  // English Strings
  static const Map<String, String> en = {
    'app_name': 'Smart Expenses Plan',
    'welcome_back': 'Welcome Back!',
    'login': 'Login',
    'password': 'Password',
    'pin': 'PIN',
    'pattern': 'Pattern',
    'use_biometrics': 'Use Biometrics',
    'skip_for_now': 'Skip for now',
    'forgot_password': 'Forgot Password?',
    'forgot_pattern': 'Forgot Pattern?',
    'home': 'Home',
    'calendar': 'Calendar',
    'calculator': 'Calculator',
    'compare': 'Compare',
    'profile': 'Profile',
    'add_payment': 'Add Payment Plan',
    'add_expense': 'Add Expense',
    'payment_name': 'Payment Name',
    'amount': 'Amount',
    'currency': 'Currency',
    'bill_type': 'Bill Type',
    'reference': 'Reference',
    'payment_date': 'Payment Date',
    'payer_name': 'Payer Name',
    'payee_name': 'Payee Name',
    'payment_method': 'Payment Method',
    'payer_service': 'Payer Service',
    'payee_service': 'Payee Service',
    'fees': 'Transaction Fees',
    'total_amount': 'Total Amount',
    'enable_reminder': 'Enable Reminder',
    'notes': 'Notes',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'search': 'Search',
    'recent_activity': 'Recent Activity',
    'view_all': 'View All',
    'income': 'Income',
    'upcoming': 'Upcoming',
    'paid': 'Paid',
    'missed': 'Missed',
    'expenses': 'Expenses',
    'categories': 'Categories',
    'quick_actions': 'Quick Actions',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'language': 'Language',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'system_default': 'System Default',
    'backup': 'Backup',
    'restore': 'Restore',
    'export': 'Export',
    'import': 'Import',
    'clear_data': 'Clear Data',
    'logout': 'Logout',
    'about': 'About',
    'feedback': 'Feedback',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'version': 'Version',
    'developer': 'Developer',
    'manager': 'Manager',
    'total_payments': 'Total Payments',
    'total_expenses': 'Total Expenses',
    'upcoming_payments': 'Upcoming Payments',
    'missed_payments': 'Missed Payments',
    'paid_this_month': 'Paid This Month',
    'spend_by_category': 'Spend by Category',
    'payment_history': 'Payment History',
    'expense_history': 'Expense History',
    'export_pdf': 'Export to PDF',
    'export_excel': 'Export to Excel',
    'export_csv': 'Export to CSV',
    'backup_to_cloud': 'Backup to Cloud',
    'restore_from_cloud': 'Restore from Cloud',
    'select_cloud': 'Select Cloud Provider',
    'backup_frequency': 'Backup Frequency',
    'last_backup': 'Last Backup',
    'biometric_login': 'Biometric Login',
    'cloud_account': 'Cloud Account',
    'connect_account': 'Connect Account',
    'disconnect': 'Disconnect',
    'are_you_sure': 'Are you sure?',
    'confirm': 'Confirm',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading...',
    'no_data': 'No data available',
    'retry': 'Retry',
    'welcome': 'Welcome to Smart Expenses Plan',
    'terms_accept': 'I accept the Terms of Service',
    'continue': 'Continue',
    'setup_pin': 'Setup PIN',
    'setup_pattern': 'Setup Pattern',
    'confirm_pin': 'Confirm PIN',
    'confirm_pattern': 'Confirm Pattern',
    'pin_mismatch': 'PIN does not match',
    'pattern_mismatch': 'Pattern does not match',
    'enter_pin': 'Enter your PIN',
    'draw_pattern': 'Draw your pattern',
    'biometric_prompt': 'Please authenticate to access your account',
  };

  // Swahili Strings
  static const Map<String, String> sw = {
    'app_name': 'Smart Expenses Plan',
    'welcome_back': 'Karibu Tena!',
    'login': 'Ingia',
    'password': 'Nywila',
    'pin': 'Namba ya siri',
    'pattern': 'Muundo',
    'use_biometrics': 'Tumia alama za vidole',
    'skip_for_now': 'Ruka kwa sasa',
    'forgot_password': 'Umesahau nywila?',
    'forgot_pattern': 'Umesahau muundo?',
    'home': 'Nyumbani',
    'calendar': 'Kalenda',
    'calculator': 'Kikokotoo',
    'compare': 'Linganisha',
    'profile': 'Wasifu',
    'add_payment': 'Ongeza Malipo',
    'add_expense': 'Ongeza Gharama',
    'payment_name': 'Jina la Malipo',
    'amount': 'Kiasi',
    'currency': 'Sarafu',
    'bill_type': 'Aina ya Bili',
    'reference': 'Marejeleo',
    'payment_date': 'Tarehe ya Malipo',
    'payer_name': 'Jina la Mlipaji',
    'payee_name': 'Jina la Mlipwaji',
    'payment_method': 'Njia ya Malipo',
    'payer_service': 'Huduma ya Mlipaji',
    'payee_service': 'Huduma ya Mlipwaji',
    'fees': 'Ada',
    'total_amount': 'Jumla',
    'enable_reminder': 'Washa ukumbusho',
    'notes': 'Maelezo',
    'save': 'Hifadhi',
    'cancel': 'Ghairi',
    'delete': 'Futa',
    'edit': 'Hariri',
    'search': 'Tafuta',
    'recent_activity': 'Shughuli za Hivi Karibuni',
    'view_all': 'Angalia Zote',
    'income': 'Mapato',
    'upcoming': 'Yanayokuja',
    'paid': 'Yaliyolipwa',
    'missed': 'Yaliyokosekana',
    'expenses': 'Gharama',
    'categories': 'Aina',
    'quick_actions': 'Vitendo vya Haraka',
    'settings': 'Mipangilio',
    'notifications': 'Arifa',
    'language': 'Lugha',
    'theme': 'Mandhari',
    'dark_mode': 'Mandhari ya Giza',
    'light_mode': 'Mandhari ya Mwanga',
    'system_default': 'Mfumo',
    'backup': 'Hifadhi rudufu',
    'restore': 'Rejesha',
    'export': 'Hamisha',
    'import': 'Ingiza',
    'clear_data': 'Futa Data',
    'logout': 'Toka',
    'about': 'Kuhusu',
    'feedback': 'Maoni',
    'terms_of_service': 'Masharti ya Huduma',
    'privacy_policy': 'Sera ya Faragha',
    'version': 'Toleo',
    'developer': 'Msanidi',
    'manager': 'Meneja',
    'total_payments': 'Jumla ya Malipo',
    'total_expenses': 'Jumla ya Gharama',
    'upcoming_payments': 'Malipo Yajayo',
    'missed_payments': 'Malipo Yaliyokosa',
    'paid_this_month': 'Yaliyolipwa Mwezi Huu',
    'spend_by_category': 'Matumizi kwa Aina',
    'payment_history': 'Historia ya Malipo',
    'expense_history': 'Historia ya Gharama',
    'export_pdf': 'Hamisha kwa PDF',
    'export_excel': 'Hamisha kwa Excel',
    'export_csv': 'Hamisha kwa CSV',
    'backup_to_cloud': 'Hifadhi kwenye wingu',
    'restore_from_cloud': 'Rejesha kutoka wingu',
    'select_cloud': 'Chagua huduma ya wingu',
    'backup_frequency': 'Mara ngapi kuhifadhi',
    'last_backup': 'Hifadhi ya mwisho',
    'biometric_login': 'Ingia kwa alama za vidole',
    'cloud_account': 'Akaunti ya wingu',
    'connect_account': 'Unganisha akaunti',
    'disconnect': 'Tenganisha',
    'are_you_sure': 'Una uhakika?',
    'confirm': 'Thibitisha',
    'success': 'Imefanikiwa',
    'error': 'Hitilafu',
    'loading': 'Inapakia...',
    'no_data': 'Hakuna data',
    'retry': 'Jaribu tena',
    'welcome': 'Karibu kwenye Smart Expenses Plan',
    'terms_accept': 'Ninakubali Masharti ya Huduma',
    'continue': 'Endelea',
    'setup_pin': 'Weka PIN',
    'setup_pattern': 'Weka muundo',
    'confirm_pin': 'Thibitisha PIN',
    'confirm_pattern': 'Thibitisha muundo',
    'pin_mismatch': 'PIN hailingani',
    'pattern_mismatch': 'Muundo haufanani',
    'enter_pin': 'Weka PIN yako',
    'draw_pattern': 'Chora muundo wako',
    'biometric_prompt': 'Tafadhali thibitisha utambulisho wako',
  };
}